#!/usr/bin/env bash

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

echo "--> Bootstrapping application"

script/bootstrap

echo "--> Done"

echo "--> Launching containers"

script/server

echo "--> Containers running..."

echo "--> Testing application"

script/test

echo "--> Setup complete.. access localhost:8000/user in browser"